apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: 'true'
  creationTimestamp: '2018-07-17T11:31:46Z'
  generation: 2
  labels:
    app: oauth2-debugger
    template: oauth2-debugger
  name: oauth2-debugger
  namespace: test
  resourceVersion: '48992'
  selfLink: /apis/apps.openshift.io/v1/namespaces/test/deploymentconfigs/oauth2-debugger
  uid: fd286963-89b4-11e8-b29e-0a6e2849c91e
spec:
  replicas: 1
  selector:
    name: oauth2-debugger
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: oauth2-debugger
      name: oauth2-debugger
    spec:
      containers:
        - image: >-
            jdelagal/oauth2-oidc-debugger@sha256:ef683718b3a4d932c65f890b88eccc46efed845413c2e269084cd7da3eb5132d
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: oauth2-debugger
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - oauth2-debugger
        from:
          kind: ImageStreamTag
          name: 'jdelagal/oauth2-oidc-debugger:latest'
          namespace: test
        lastTriggeredImage: >-
          jdelagal/oauth2-oidc-debugger@sha256:ef683718b3a4d932c65f890b88eccc46efed845413c2e269084cd7da3eb5132d
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-07-17T11:33:47Z'
      lastUpdateTime: '2018-07-17T11:33:47Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-07-17T11:33:38Z'
      lastUpdateTime: '2018-07-17T11:33:48Z'
      message: replication controller "oauth2-debugger" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
