apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: apim
  name: apim
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ibmcom/apiconnect:manager-v5.0.6.0
    generation: null
    importPolicy: {}
    name: manager-v5.0.6.0
status:
  dockerImageRepository: ""
