apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: datapower
  name: datapower
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: datapower
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
