apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\QUERETARO\TOOLS\kompose\kompose.exe --provider openshift --file
      docker-compose.yaml convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: datapower
  name: datapower
spec:
  replicas: 1
  selector:
    io.kompose.service: datapower
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: datapower
    spec:
      containers:
      - env:
        - name: DATAPOWER_ACCEPT_LICENSE
          value: "true"
        image: ' '
        name: datapower
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - datapower
      from:
        kind: ImageStreamTag
        name: datapower:latest
    type: ImageChange
status: {}
