apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: esmaster
  name: esmaster
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: esmaster
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
