apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ibmportal
  name: ibmportal
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ibmcom/apiconnect:portal-v5.0.6.0
    generation: null
    importPolicy: {}
    name: portal-v5.0.6.0
status:
  dockerImageRepository: ""
