apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ibmcom/apiconnect:logstash-v5.0.6.0
    generation: null
    importPolicy: {}
    name: logstash-v5.0.6.0
status:
  dockerImageRepository: ""
