apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: make-ssh-keys
  name: make-ssh-keys
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: make-ssh-keys
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
