apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: microservice
  name: microservice
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: microservice
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
