apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\QUERETARO\TOOLS\kompose\kompose.exe --provider openshift --file
      docker-compose.yaml convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    io.kompose.service: nginx
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - env:
        - name: APIM_DNS
          value: apim
        - name: GATEWAY_DNS
          value: datapower
        - name: PORTAL_DNS
          value: ibmportal
        image: ' '
        name: nginx
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nginx
      from:
        kind: ImageStreamTag
        name: nginx:latest
    type: ImageChange
status: {}
