apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\QUERETARO\TOOLS\kompose\kompose.exe --provider openshift --file
      docker-compose.yml convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: hydra
  name: hydra
spec:
  replicas: 1
  selector:
    io.kompose.service: hydra
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hydra
    spec:
      containers:
      - args:
        - --dangerous-force-http
        - --dangerous-auto-logon
        - --disable-telemetry
        env:
        - name: CONSENT_URL
          value: http://localhost:3000/consent
        - name: DATABASE_URL
          value: postgres://userFMB:FBrdsdetb0KEftF6@postgresql:5432/sampledb?sslmode=disable
        - name: FORCE_ROOT_CLIENT_CREDENTIALS
          value: admin:admin-password
        - name: ISSUER
          value: https://localhost:4444
        - name: SYSTEM_SECRET
          value: youReallyNeedToChangeThis
        image: ' '
        name: hydra
        ports:
        - containerPort: 4444
        resources: {}
        volumeMounts:
        - mountPath: /root
          name: version0-hydravolume
      restartPolicy: Always
      volumes:
      - name: version0-hydravolume
        persistentVolumeClaim:
          claimName: version0-hydravolume
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - hydra
      from:
        kind: ImageStreamTag
        name: hydra:latest
    type: ImageChange
status: {}
