apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: consent
  name: consent
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: oryd/hydra-consent-app-express:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
