apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: consent
  name: consent
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: oryd/hydra-login-consent-node:v1.0.0-beta.1
    generation: null
    importPolicy: {}
    name: v1.0.0-beta.1
status:
  dockerImageRepository: ""
