apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hydra
  name: hydra
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: oryam/hydra:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
