apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\QUERETARO\TOOLS\kompose\kompose.exe --provider openshift --file
      docker-compose.yml convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: hydra
  name: hydra
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  - name: "4445"
    port: 4445
    targetPort: 4445
  selector:
    io.kompose.service: hydra
status:
  loadBalancer: {}
