apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\QUERETARO\TOOLS\kompose\kompose.exe --provider openshift --file
      docker-compose.yml convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: hydra
  name: hydra
spec:
  replicas: 1
  selector:
    io.kompose.service: hydra
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hydra
    spec:
      containers:
      - args:
        - hydra
        - host
        - --dangerous-auto-logon
        env:
        - name: DATABASE_URL
          value: postgres://userR6U:MrFtH8wDLPNJsWdE@postgresql:5432/sampledb?sslmode=disable
        - name: OAUTH2_CONSENT_URL
          value: https://localhost:3000/consent
        - name: OAUTH2_ISSUER_URL
          value: https://localhost:4444
        - name: OAUTH2_LOGIN_URL
          value: https://localhost:3000/login
        - name: OAUTH2_SHARE_ERROR_DEBUG
          value: "1"
        - name: SYSTEM_SECRET
          value: youReallyNeedToChangeThis
        - name: HTTPS_ALLOW_TERMINATION_FROM
          value: 0.0.0.0/0
        image: ' '
        name: hydra
        ports:
        - containerPort: 4444
        - containerPort: 4445
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - hydra
      from:
        kind: ImageStreamTag
        name: hydra:latest
    type: ImageChange
status: {}
