apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgresd
  name: postgresd
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: postgres:9.6
    generation: null
    importPolicy: {}
    name: "9.6"
status:
  dockerImageRepository: ""
